from __future__ import annotations
import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether


def _escape(text: Any) -> str:
    return str(text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>")


def _p(text: Any, style):
    return Paragraph(_escape(text), style)


def _kv(key: str, value: Any, style):
    return Paragraph(f"<b>{_escape(key)}</b>: {_escape(value)}", style)


def _num(value: Any) -> float | None:
    try:
        if str(value).strip() == "":
            return None
        return float(str(value).replace(",", "."))
    except Exception:
        return None


def _pre_band(total: Any) -> str:
    x = _num(total)
    if x is None:
        return "Not scored"
    if x >= 24: return "Highly recommended"
    if x >= 20: return "Recommended"
    if x >= 16: return "Borderline / panel review"
    return "Not recommended"


def _int_band(total: Any) -> str:
    x = _num(total)
    if x is None:
        return "Not scored"
    if x >= 41: return "Highly recommended"
    if x >= 31: return "Recommended"
    if x >= 21: return "Moderately recommended"
    return "Not recommended"


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.drawString(doc.leftMargin, 8*mm, 'This report is generated by the "RAUN Apps - SM".')
    canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 8*mm, f"Page {doc.page}")
    canvas.restoreState()


def _table(rows, widths, header_color="#1D4ED8"):
    t = Table(rows, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.25, colors.HexColor("#CBD5E1")),
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor(header_color)),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 4),
        ("RIGHTPADDING", (0,0), (-1,-1), 4),
        ("TOPPADDING", (0,0), (-1,-1), 4),
        ("BOTTOMPADDING", (0,0), (-1,-1), 4),
    ]))
    return t


def candidate_assessment_pdf(candidate: dict, mode: str = "preselection") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=14*mm, leftMargin=14*mm, topMargin=14*mm, bottomMargin=16*mm)
    styles = getSampleStyleSheet()
    title = ParagraphStyle("RAUNTitle", parent=styles["Title"], fontSize=16, leading=20, spaceAfter=8, textColor=colors.HexColor("#0F172A"))
    h = ParagraphStyle("RAUNHeading", parent=styles["Heading2"], fontSize=11, leading=14, spaceBefore=8, spaceAfter=5, textColor=colors.HexColor("#0F172A"))
    normal = ParagraphStyle("RAUNNormal", parent=styles["Normal"], fontSize=8.0, leading=10)
    small = ParagraphStyle("RAUNSmall", parent=styles["Normal"], fontSize=7.2, leading=9)
    story = []
    story.append(_p("RAUN Candidate Assessment Report", title))
    story.append(_p(f"Mode: {'Interview scoring' if mode == 'interview' else 'Pre-selection review'}", small))
    story.append(_p(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", small))
    story.append(Spacer(1, 4))

    basic_rows = [[_p("Field", small), _p("Value", small)]]
    for key in ["Applicant ID", "Full Name", "Email", "Program", "University", "Field", "Age", "Country of Residence", "Country of Citizenship", "Reviewer 1", "Reviewer 2", "Interviewer"]:
        basic_rows.append([_p(key, small), _p(candidate.get(key, ""), small)])
    story.append(_table(basic_rows, [48*mm, 126*mm], "#0F172A"))

    story.append(_p("Score bands", h))
    band_rows = [[_p("Score item", small), _p("Value", small), _p("Band / status", small)]]
    for label, val in [("Reviewer 1 pre-selection", candidate.get("R1 Total", "")), ("Reviewer 2 pre-selection", candidate.get("R2 Total", "")), ("Combined first review", candidate.get("Total points from both reviewers", ""))]:
        band_rows.append([_p(label, small), _p(val, small), _p(_pre_band(val if label != "Combined first review" else (_num(val) / 2 if _num(val) is not None else "")), small)])
    if mode == "interview":
        band_rows.append([_p("Interview", small), _p(candidate.get("Interview Total", ""), small), _p(_int_band(candidate.get("Interview Total", "")), small)])
        band_rows.append([_p("Final decision", small), _p(candidate.get("Final Total", ""), small), _p(candidate.get("Final Decision", ""), small)])
    story.append(_table(band_rows, [55*mm, 35*mm, 84*mm], "#334155"))

    story.append(_p("Application notes", h))
    any_note = False
    for key in ["Graduate Track Motivation", "Research Project Responsibility", "Self-rated Research Experience", "Self-rated Written English", "Self-rated Oral English", "Scholarship Motivation", "Accessibility Requirements", "Accessibility Details", "Area 1", "Area 2", "Area 3"]:
        if str(candidate.get(key, "")).strip():
            story.append(_kv(key, candidate.get(key), normal))
            story.append(Spacer(1, 3))
            any_note = True
    if not any_note:
        story.append(_p("No application notes available in the loaded sheet.", small))

    story.append(_p("Pre-selection scores", h))
    pre_rows = [[_p("Criterion", small), _p("Reviewer 1", small), _p("Reviewer 2", small)]]
    for label in ["Research", "International", "English", "Personality", "Motivation", "Grades", "Total", "Invitation", "Top5", "Comment"]:
        pre_rows.append([_p(label, small), _p(candidate.get(f"R1 {label}", ""), small), _p(candidate.get(f"R2 {label}", ""), small)])
    pre_rows.append([_p("Derived First Review Result", small), _p(candidate.get("Derived First Review Result", ""), small), _p("Interview Required: " + str(candidate.get("Interview Required", "")), small)])
    story.append(_table(pre_rows, [48*mm, 63*mm, 63*mm], "#1D4ED8"))

    if mode == "interview":
        story.append(PageBreak())
        story.append(_p("Interview scores", h))
        int_rows = [[_p("Criterion", small), _p("Score / value", small)]]
        for col in ["Interview Motivation", "Interview International", "Interview Research", "Interview Professionalism", "Interview Respect Diversity", "Interview Communication English", "Interview Teamwork", "Interview Planning Organization", "Interview Availability", "Interview UN Knowledge", "Interview Total", "Interview Recommended", "Interview Top5", "Interview Comment", "Final Total", "Final Decision"]:
            int_rows.append([_p(col, small), _p(candidate.get(col, ""), small)])
        story.append(_table(int_rows, [72*mm, 102*mm], "#0F766E"))

    story.append(Spacer(1, 6))
    story.append(_p('This report is generated by the "RAUN Apps - SM".', small))
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    buf.seek(0)
    return buf.getvalue()


def candidate_assessment_docx(candidate: dict, mode: str = "preselection") -> bytes:
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.add_heading("RAUN Candidate Assessment Report", level=1)
    doc.add_paragraph(f"Mode: {'Interview scoring' if mode == 'interview' else 'Pre-selection review'}")
    doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    doc.add_heading("Candidate details", level=2)
    table = doc.add_table(rows=1, cols=2); table.style = "Table Grid"
    table.rows[0].cells[0].text = "Field"; table.rows[0].cells[1].text = "Value"
    for key in ["Applicant ID", "Full Name", "Email", "Program", "University", "Field", "Age", "Country of Residence", "Country of Citizenship", "Reviewer 1", "Reviewer 2", "Interviewer"]:
        row = table.add_row().cells; row[0].text = key; row[1].text = str(candidate.get(key, ""))

    doc.add_heading("Score bands", level=2)
    bt = doc.add_table(rows=1, cols=3); bt.style = "Table Grid"
    bt.rows[0].cells[0].text = "Score item"; bt.rows[0].cells[1].text = "Value"; bt.rows[0].cells[2].text = "Band / status"
    for label, val in [("Reviewer 1 pre-selection", candidate.get("R1 Total", "")), ("Reviewer 2 pre-selection", candidate.get("R2 Total", "")), ("Combined first review", candidate.get("Total points from both reviewers", ""))]:
        row = bt.add_row().cells; row[0].text = label; row[1].text = str(val); row[2].text = _pre_band(val if label != "Combined first review" else (_num(val) / 2 if _num(val) is not None else ""))
    if mode == "interview":
        row = bt.add_row().cells; row[0].text = "Interview"; row[1].text = str(candidate.get("Interview Total", "")); row[2].text = _int_band(candidate.get("Interview Total", ""))
        row = bt.add_row().cells; row[0].text = "Final decision"; row[1].text = str(candidate.get("Final Total", "")); row[2].text = str(candidate.get("Final Decision", ""))

    doc.add_heading("Application notes", level=2)
    had = False
    for key in ["Graduate Track Motivation", "Research Project Responsibility", "Self-rated Research Experience", "Self-rated Written English", "Self-rated Oral English", "Scholarship Motivation", "Accessibility Requirements", "Accessibility Details", "Area 1", "Area 2", "Area 3"]:
        value = str(candidate.get(key, "")).strip()
        if value:
            p = doc.add_paragraph(); run = p.add_run(f"{key}: "); run.bold = True; p.add_run(value); had = True
    if not had: doc.add_paragraph("No application notes available in the loaded sheet.")

    doc.add_heading("Pre-selection scores", level=2)
    t = doc.add_table(rows=1, cols=3); t.style = "Table Grid"
    t.rows[0].cells[0].text = "Criterion"; t.rows[0].cells[1].text = "Reviewer 1"; t.rows[0].cells[2].text = "Reviewer 2"
    for label in ["Research", "International", "English", "Personality", "Motivation", "Grades", "Total", "Invitation", "Top5", "Comment"]:
        row = t.add_row().cells; row[0].text = label; row[1].text = str(candidate.get(f"R1 {label}", "")); row[2].text = str(candidate.get(f"R2 {label}", ""))
    row = t.add_row().cells; row[0].text = "Derived First Review Result"; row[1].text = str(candidate.get("Derived First Review Result", "")); row[2].text = "Interview Required: " + str(candidate.get("Interview Required", ""))

    if mode == "interview":
        doc.add_page_break(); doc.add_heading("Interview scores", level=2)
        t = doc.add_table(rows=1, cols=2); t.style = "Table Grid"; t.rows[0].cells[0].text = "Criterion"; t.rows[0].cells[1].text = "Score / value"
        for col in ["Interview Motivation", "Interview International", "Interview Research", "Interview Professionalism", "Interview Respect Diversity", "Interview Communication English", "Interview Teamwork", "Interview Planning Organization", "Interview Availability", "Interview UN Knowledge", "Interview Total", "Interview Recommended", "Interview Top5", "Interview Comment", "Final Total", "Final Decision"]:
            row = t.add_row().cells; row[0].text = col; row[1].text = str(candidate.get(col, ""))

    doc.add_paragraph('This report is generated by the "RAUN Apps - SM".')
    bio = io.BytesIO(); doc.save(bio); bio.seek(0); return bio.getvalue()
